# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  encoding: UTF8
  timeout: 5000

development:
  <<: *default
  database: postgresql_development
  username: liangtai1
  password: postgresql
  host: localhost

test:
  <<: *default
  database: postgresql
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: d6nvo5cqds9rqo
  username: keltchlnegodhz
  password: f7727ac6be1d874abb32e5aea793ae4d71f9878e902fe99917cd7361ffb94af4
  port: 5432
  host: ec2-54-204-46-236.compute-1.amazonaws.com